include_cookbook 'common-definitions'
include_cookbook 'yum/epel'
include_cookbook 'yum/remi'
include_cookbook 'yum/mysql'
include_cookbook 'yum/nginx'
include_cookbook 'yum/zabbix'
include_cookbook 'yum/owncloud'
